[build]
  command = "node --version && npm --version && npm ci && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.1.2"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "./netlify/plugins/ignore-engines"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200